In [ ]:
import numpy as np

In [ ]:
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
print("La liste est :", list_1)


La liste est : [50, 60, 80, 100, 200, 300, 500, 600]


In [ ]:
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [ ]:
type(my_numpy_array)

numpy.ndarray

In [ ]:
my_matrix = np.array([[2, 4, 8],[1, 2, 4]])
my_matrix

array([[2, 4, 8],
       [1, 2, 4]])

In [ ]:
x = np.random.rand(20)
x

array([0.50182804, 0.29771035, 0.31614086, 0.60086503, 0.37285412,
       0.60617507, 0.00390503, 0.24772734, 0.42138252, 0.07824074,
       0.05537608, 0.3444364 , 0.98283414, 0.57955235, 0.0431454 ,
       0.54310261, 0.03486408, 0.69403138, 0.3845444 , 0.17737211])

In [ ]:
x = np.random.rand(3, 3)
x

array([[0.26702298, 0.02286278, 0.51167753],
       [0.65386387, 0.91633519, 0.65223144],
       [0.62470215, 0.3162863 , 0.84100128]])

In [ ]:
x = np.random.randint(1, 50)
x

28

In [ ]:
x = np.random.randint(1, 100, 15)
x

array([60, 44, 48, 25, 70, 69, 85, 76, 11, 19, 30, 15, 45, 95, 52])

In [ ]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
x = np.eye(10)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x = int(input("Please enter a positive integer number:"))

Please enter a positive integer number:20


In [ ]:
x

20

In [ ]:
x = np.random.randint(1, x, 10)
x

array([14, 16, 13,  8,  9,  3, 17,  1,  9, 15])

In [ ]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
squarred = x ** 2
squarred

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
sqrt = np.sqrt(squarred)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [ ]:
x = np.array([5, 7, 20])
y = np.array([9, 14, 4])
z = np.sqrt(x ** 2 + y ** 2)
z

array([10.29563014, 15.65247584, 20.39607805])

In [ ]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [ ]:
#Access to the elements by the index
my_numpy_array[-1]


50

In [ ]:
my_numpy_array[0:3]


array([3, 5, 6])

In [ ]:
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [ ]:
matrix = np.random.randint(1, 10, (4,4))
matrix

array([[2, 5, 8, 3],
       [1, 1, 4, 7],
       [3, 7, 6, 6],
       [4, 2, 4, 6]])

In [ ]:
matrix[0]

array([2, 5, 8, 3])

In [ ]:
matrix[1, 3]

7

In [ ]:
matrix[2,2]

6

Access to the last number of the array


In [ ]:
matrix[3, -1]

6

In [ ]:
x = np.array ([[2, 30, 20, -2, -4],
                    [3, 4, 40, -3, -2],
                    [-3, 4, -6, 90, 10],
                    [25, 45, 34, 22, 12],
                    [13, 24, 22, 32, 37]])
x


array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [ ]:
x[4, 4] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [ ]:
matrix = np.random.randint(1, 10, (5,5))
matrix

array([[2, 2, 7, 5, 7],
       [4, 5, 6, 3, 4],
       [9, 4, 2, 1, 5],
       [3, 3, 2, 8, 4],
       [9, 3, 2, 3, 5]])

In [ ]:
new_matrix = matrix [matrix > 7]
new_matrix


array([9, 8, 9])

In [ ]:
new_matrix = matrix[matrix % 2 == 1]
new_matrix

array([7, 5, 7, 5, 3, 9, 1, 5, 3, 3, 9, 3, 3, 5])

In [ ]:
new_matrix = matrix[matrix % 2 == 0]
new_matrix

array([2, 2, 4, 6, 4, 4, 2, 2, 8, 4, 2])

In [ ]:
x =np.array ([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [ ]:
x[ x < 0]= 0
x[ x% 2 == 1] =-2

x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

In [ ]:
import pandas as pd

In [ ]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3,4,9,5]})

In [ ]:
bank_client_df

Bank Clien ID Bank Client Name  Net Worth [$]  Years with bank
0            111           Chanel           3500                3
1            222            Steve          29000                4
2            333            Mitch          10000                9
3            444             Ryan           2000                5

In [ ]:
bank_client_df.columns

In [ ]:
bank_client_df['Bank Client Name'].std

<bound method NDFrame._add_numeric_operations.<locals>.std of 0    Chanel
1     Steve
2     Mitch
3      Ryan
Name: Bank Client Name, dtype: object>

In [ ]:
type(bank_client_df)

pandas.core.frame.DataFrame

In [ ]:
bank_client_df.head(2)

Bank Clien ID Bank Client Name  Net Worth [$]  Years with bank
0            111           Chanel           3500                3
1            222            Steve          29000                4

In [ ]:
bank_client_df.tail(2)

Bank Clien ID Bank Client Name  Net Worth [$]  Years with bank
2            333            Mitch          10000                9
3            444             Ryan           2000                5

In [ ]:
portofolio_df = pd.DataFrame ({'Stock ticker symbol':['AAPL','AMZN','T'],
                               'Price per share [$]':[3500, 200, 40],
                               'Number of stocks':[3,4,9]})
portofolio_df

Stock ticker symbol  Price per share [$]  Number of stocks
0                AAPL                 3500                 3
1                AMZN                  200                 4
2                   T                   40                 9

In [ ]:
stock_dollar_value = portofolio_df['Number of stocks'] * portofolio_df['Price per share [$]']
stock_dollar_value.sum()

11660

In [ ]:
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [ ]:
!pip install lxml

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [ ]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [ ]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html ')
retirement_df[0]

In [ ]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3,4,9,5]})

In [ ]:
df_loyal = bank_client_df[bank_client_df['Years with bank']>= 5]
df_loyal

In [ ]:
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

In [ ]:
df_high_networth = bank_client_df[bank_client_df['Net Worth [$]']>= 5000]
df_high_networth

Bank Client Name  Net Worth [$]  Years with bank
1            Steve          29000                4
2            Mitch          10000                9

In [ ]:
df_high_networth['Net Worth [$]'].sum()

39000

In [ ]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3,4,9,5]})

In [ ]:
bank_client_df


Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
def networth_update(balance):
     return balance * 1.2

In [ ]:
bank_client_df['Net Worth [$]'].apply(networth_update)


In [ ]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

In [ ]:
def networth_update(balance):
     return balance * 3 + 200

In [ ]:
results = bank_client_df['Net Worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net Worth [$], dtype: int64

In [ ]:
results.sum()

134300

In [ ]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3,4,9,5]})

In [ ]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
bank_client_df.sort_values(by ='Years with bank')

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [ ]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
bank_client_df.sort_values(by ='Years with bank', inplace=True)

In [ ]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [ ]:
df1 = pd.DataFrame({'A':['A0', 'A1','A2','A3'],
                    'B':['B0', 'B1','B2','B3'],
                    'C':['C0', 'C1','C2','C3'],
                    'D':['D0', 'D1','D2','D3']},
                   index = [0, 1, 2, 3])


In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2 = pd.DataFrame({'A':['A4', 'A5','A6','A7'],
                    'B':['B4', 'B5','B6','B7'],
                    'C':['C4', 'C5','C6','C7'],
                    'D':['D4', 'D5','D6','D7']},
                   index = [0, 1, 2, 3])

In [ ]:
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
df3 = pd.DataFrame({'A':['A8', 'A9','A10','A11'],
                    'B':['B8', 'B9','B10','B11'],
                    'C':['C8', 'C9','C10','C11'],
                    'D':['D8', 'D9','D10','D11']},
                   index = [0, 1, 2, 3])

In [ ]:
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
dfTotal = pd.concat([df1,df2,df3])


In [ ]:
dfTotal

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
raw_data = {'Bank Client ID':['1','2', '3', '4', '5'],
            'First Name':['Nancy','Alex', 'Shep', 'Max', 'Allen'],
            'Last Name':['Rob','Ali', 'George', 'Mitch', 'Steve']}

In [ ]:
bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID','First Name','Last Name'])


In [ ]:
bank_df_1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [ ]:
raw_data = {'Bank Client ID':['6','7', '8', '9', '10'],
            'First Name':['Bill','Dina', 'Sarah', 'Heather', 'Molly'],
            'Last Name':['Christian','Mo', 'Steve', 'Rob', 'Michelle']}

In [ ]:
bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID','First Name','Last Name'])

In [ ]:
bank_df_2

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [ ]:
raw_data = {'Bank Client ID':['1','2', '3', '4', '5', '6','7', '8', '9', '10'],
            'Annual Salary [$]':[25000, 35000, 45000, 480000, 49000, 32000, 33000, 34000, 23000, 22000]}

In [ ]:
bank_df_salary = pd.DataFrame(raw_data, columns=['Bank Client ID', 'Annual Salary [$]'])


In [ ]:
bank_df_salary

Bank Client ID  Annual Salary [$]
0              1              25000
1              2              35000
2              3              45000
3              4             480000
4              5              49000
5              6              32000
6              7              33000
7              8              34000
8              9              23000
9             10              22000

In [ ]:
bank_df_all = pd.concat([bank_df_1, bank_df_2])


In [ ]:
bank_df_all

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [ ]:
dt = np.array([[3, 7, 9, 3],[4, 3, 2, 2]])

In [ ]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID' )

In [ ]:
bank_df_all

Bank Client ID First Name Last Name  Annual Salary [$]
0              1      Nancy       Rob              25000
1              1      Nancy       Rob              25000
2              2       Alex       Ali              35000
3              2       Alex       Ali              35000
4              3       Shep    George              45000
5              3       Shep    George              45000
6              4        Max     Mitch             480000
7              4        Max     Mitch             480000
8              5      Allen     Steve              49000
9              5      Allen     Steve              49000

In [ ]:
from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_10['Bank Client ID'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_10, x='index', y='Bank Client ID', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
new_client = {'Bank Client':['11'],
             'First Name':['Ryan'],
              'Last Name':['Ahmed'],
              'Annual Salary [$]':[5000]}

new_client_df = pd.DataFrame(new_client, columns = ['Bank Client', 'First Name', 'Last Name', 'Annual Salary [$]'])


In [ ]:
new_client_df

Bank Client First Name Last Name  Annual Salary [$]
0          11       Ryan     Ahmed               5000

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name Last Name  Annual Salary [$] Bank Client
0              1      Nancy       Rob              25000         NaN
1              1      Nancy       Rob              25000         NaN
2              2       Alex       Ali              35000         NaN
3              2       Alex       Ali              35000         NaN
4              3       Shep    George              45000         NaN
5              3       Shep    George              45000         NaN
6              4        Max     Mitch             480000         NaN
7              4        Max     Mitch             480000         NaN
8              5      Allen     Steve              49000         NaN
9              5      Allen     Steve              49000         NaN
0            NaN       Ryan     Ahmed               5000          11

In [ ]:
dt

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])